name: dysurf-rep_flowDNeRF_200k_NDRLoss-${dataset.scene}
tag: ''
seed: 42

dataset:
  name: dysurf_dataset
  scene: ???
  root_dir: ./load/${dataset.scene}
  img_wh:
    - ${system.resolution}
    - ${system.resolution}
  train_split: 'train'
  train_ids: [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49]
  val_split: 'val'
  val_ids: [20, 35]
  test_split: 'test'
  test_ids: [5, 20, 35, 45]

model:
  name: dysurf
  max_timestep: 50

  deform_network_cls: 'flownet.DeformDNeRF'
  disable_topo_network: True

  radius: 1.0
  train_num_rays: 512 #512
  ray_chunk: 1024
  batch_image_sampling: false
  randomized: false
  cos_anneal_end: 0
  pc_anneal_end: 50000

  isosurface:
    resolution: 512

  sampling:
    n_samples: 64
    n_importance: 64
    n_outside: 0
    up_sample_steps: 4     # 1 for simple coarse-to-fine sampling
    perturb: 1.0

  variance:
    init_val: 0.3
    modulate: false

  sdf_network:
    d_out: 257
    d_in_1: 3
    d_in_2: 2
    d_hidden: 256
    n_layers: 8
    skip_in: [4]
    multires: 6
    multires_topo: 1
    bias: 0.5
    scale: 1.0
    geometric_init: True
    weight_norm: True

  appearance_rendering_network:
    d_feature: 256
    d_global_feature: 64
    mode: 'idr'
    d_in: 9
    d_out: 3
    d_hidden: 256
    n_layers: 4
    weight_norm: True
    multires_view: 4
    squeeze_out: True

  deform_network:
    d_time: 1  # time dimension
    d_in: 3
    multires: 0

  topo_network:
    d_feature: 64
    d_in: 3
    d_out: 2
    d_hidden: 64
    n_layers: 7
    skip_in: [5]
    multires: 6
    bias: 0.0
    weight_norm: True

system:
  resolution: 400
  name: dysurf-system
  vis_mesh_every: 5000
  loss:
    color_weight: 1.0
    mask_weight: 0.1
    igr_weight: 0.1
    # Depth variables
    geo_weight: 0.1
    angle_weight: 0.1
    depth_sdf_weight: 0.1
    depth_eik_weight: 0.0

  optimizer:
    name: Adam
    args:
      lr: 5e-4
  scheduler:
    warm_up_end: 5000
    learning_rate: ${system.optimizer.args.lr}
    learning_rate_alpha: 0.05
    max_steps: ${trainer.max_steps}

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

trainer:
  max_steps: 200000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 2500 #10000
  limit_train_batches: 1.0
  limit_val_batches: 2 #0.06
  enable_progress_bar: true
  inference_mode: False  # NOTE: this is supported only in pl version > 1.8
