name: dycheck-dnerf_ambient_hyper-${dataset.scene}
tag: ''
seed: 42

dataset:
  name: iPhoneDatasetFromAllFrames_dataset
  dataset: iphone
  scene: ???
  data_root: ../datasets
  train_split: 'train'
  val_split: 'val'
  test_split: 'val'

model:
  name: DynamicNeRF
  background: black
  ambient_dim: 64
  deform_dim: 64
  hyper_dim: 2

  coarse_model:
    type: AmbientNeRFMLP
    args:
      abmient_dim: ${model.ambient_dim}
      hyper_dim: ${model.hyper_dim}

  fine_model:
    type: AmbientNeRFMLP
    args:
      abmient_dim: ${model.ambient_dim}
      hyper_dim: ${model.hyper_dim}

  flow_net:
    name: mlp_flow # mlp_flow
    args:
      d_feature: ${model.deform_dim}

  hyper_net:
    name: hypernerf
    args:
      d_feature: ${model.deform_dim}
      output_dim: ${model.hyper_dim}

  sampling:
    N_samples: 128
    N_importance: 128
  
  train_num_rays: 2048 #3072 #6144
  max_train_num_rays: 2048
  batch_image_sampling: false
  randomized: true
  ray_chunk: 6144

system:
  name: tnerf-system
  loss:
    depth: 0.0
    dist: 0.0
  optimizer:
    name: Adam
    args:
      lr: 0.0005 #5e-4 0.0001
  scheduler:
    warm_up_end: 5000
    final_lr: 0.0001
    learning_rate: ${system.optimizer.args.lr}
    learning_rate_alpha: 0.05
    max_steps: ${trainer.max_steps}

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

trainer:
  max_steps: 300000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 2500 #10000
  limit_train_batches: 1.0
  limit_val_batches: 2 #0.06
  enable_progress_bar: true
