name: dysdf-${dataset.scene}
tag: ''
seed: 42

dataset:
  load_time_steps: 100
  dynamic_sequence: True
  train_split:
    - cam_train_1
    - cam_train_3
    - cam_train_6
    - cam_train_8
  val_split: 
    - cam_train_0
    - cam_train_5
  test_split: ${dataset.val_split}

  name: dysdf_dataset
  scene: ???
  data_root: ../datasets/public_data/${dataset.scene}


model:
  name: DySDF
  background: black

  ambient_dim: 0
  deform_dim: 0

  alpha_ratio:
    strategy: interpolated
    max_steps: 50000

  sampling:
    use_balanced_rays: True
    time_ray_blanced_sampling: True

    train_num_rays: 1100 #6144
    batch_image_sampling: true
    n_samples: 256
    n_importance: 0
    randomized: true
    ray_chunk: ${model.sampling.train_num_rays}

  deform_net: null
  hyper_net: null
  sdf_net:
    name: sdf_network
    n_frames: 100
    independent_layers: []
    composition_rank: 10
    d_out: 129
    d_in_1: 3
    d_in_2: 1
    d_hidden: 128
    n_layers: 8
    skip_in: [4]
    multires: 6
    multires_topo: 6
    bias: 0.5
    scale: 1.0
    geometric_init: True
    weight_norm: False
    inside_outside: False
  
  color_net:
    name: color_network
    d_hidden: 128
    n_layers: 1
    mode: 
      feature: ${sub:${model.sdf_net.d_out}, 1}
  deviation_net:
    name: laplace_density
    beta_min: 0.0001
    beta: 0.1

system:
  name: dysdf_system
  loss:
    rgb: 1.0
    mask: 0.1
    eikonal: 0.1
    dist: 0.0
  optimizer:
    name: Adam
    args:
      lr: 0.0005 #5e-4 0.0001
  scheduler:
    warm_up_end: 5000
    final_lr: 0.0001
    learning_rate: ${system.optimizer.args.lr}
    learning_rate_alpha: 0.05
    max_steps: ${trainer.max_steps}

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

trainer:
  max_steps: 250000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 2500 #10000
  limit_train_batches: 1.0
  limit_val_batches: 2 #0.06
  enable_progress_bar: true
